//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DagıtımOlcu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DagıtımOlcu()
        {
            this.DagitimOlcuFaaliyetiliski = new HashSet<DagitimOlcuFaaliyetiliski>();
            this.MaliyetUrun = new HashSet<MaliyetUrun>();
        }
    
        public int DagıtımOlcu_Id { get; set; }
        [Required(ErrorMessage ="Faaliyet Maliyet Etkenini Giriniz.")]
        public string DagıtımOlcu_Ad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DagitimOlcuFaaliyetiliski> DagitimOlcuFaaliyetiliski { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaliyetUrun> MaliyetUrun { get; set; }
    }
}
