//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BitirmeEntities : DbContext
    {
        public BitirmeEntities()
            : base("name=BitirmeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BirimMaliyet> BirimMaliyets { get; set; }
        public virtual DbSet<DagıtımOlcu> DagıtımOlcu { get; set; }
        public virtual DbSet<DagitimOlcuFaaliyetiliski> DagitimOlcuFaaliyetiliskis { get; set; }
        public virtual DbSet<Faaliyet> Faaliyets { get; set; }
        public virtual DbSet<Gider> Giders { get; set; }
        public virtual DbSet<KaynakMaliyetEtken> KaynakMaliyetEtkens { get; set; }
        public virtual DbSet<Maliyet> Maliyets { get; set; }
        public virtual DbSet<MaliyetEndirektUretim> MaliyetEndirektUretims { get; set; }
        public virtual DbSet<MaliyetUrun> MaliyetUruns { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TblBirimMaliyetTutar> TblBirimMaliyetTutars { get; set; }
        public virtual DbSet<TblToplamMaliyet> TblToplamMaliyets { get; set; }
        public virtual DbSet<TutarUrunFaaliyet> TutarUrunFaaliyets { get; set; }
        public virtual DbSet<Urun> Uruns { get; set; }
        public virtual DbSet<BirimMaliyetTutar> BirimMaliyetTutars { get; set; }
        public virtual DbSet<EndirektUretimMaliyeti> EndirektUretimMaliyetis { get; set; }
        public virtual DbSet<GenelTutar> GenelTutars { get; set; }
        public virtual DbSet<Oran> Orans { get; set; }
        public virtual DbSet<OranUrunDagitim> OranUrunDagitims { get; set; }
        public virtual DbSet<ToplamFaaliyetTutar> ToplamFaaliyetTutars { get; set; }
        public virtual DbSet<ToplamMaliyet> ToplamMaliyets { get; set; }
        public virtual DbSet<UrunFaaliyetTutar> UrunFaaliyetTutars { get; set; }
    
        public virtual ObjectResult<ProductPrice_Result> ProductPrice()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductPrice_Result>("ProductPrice");
        }
    
        public virtual int SPBirimMaliyetTutar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPBirimMaliyetTutar");
        }
    
        public virtual int SPToplamMaliyet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPToplamMaliyet");
        }
    
        public virtual int SPBirimMaliyetTutar1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPBirimMaliyetTutar1");
        }
    
        public virtual int SPBirimMaliyetTutar2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPBirimMaliyetTutar2");
        }
    
        public virtual int SPBirimMaliyetTutar3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPBirimMaliyetTutar3");
        }
    
        public virtual ObjectResult<BirimMaliyetSP_Result> BirimMaliyetSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BirimMaliyetSP_Result>("BirimMaliyetSP");
        }
    
        public virtual ObjectResult<BirimMaliyetSP_Result> BirimMaliyetSP1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BirimMaliyetSP_Result>("BirimMaliyetSP1");
        }
    }
}
