//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BitirmeEntities : DbContext
    {
        public BitirmeEntities()
            : base("name=BitirmeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Faaliyet> Faaliyet { get; set; }
        public virtual DbSet<Gider> Gider { get; set; }
        public virtual DbSet<KaynakMaliyetEtken> KaynakMaliyetEtken { get; set; }
        public virtual DbSet<Maliyet> Maliyet { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<GenelTutar> GenelTutar { get; set; }
        public virtual DbSet<Oran> Oran { get; set; }
        public virtual DbSet<ToplamFaaliyetTutar> ToplamFaaliyetTutar { get; set; }
        public virtual DbSet<DagıtımOlcu> DagıtımOlcu { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
        public virtual DbSet<UrunMaliyet> UrunMaliyet { get; set; }
    }
}
