//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunMaliyet
    {
        public int UrunMaliyet_Id { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<int> DagıtımOlcu_Id { get; set; }
        public Nullable<int> FaaliyetId { get; set; }
        public Nullable<decimal> UrunDagıtımAdet { get; set; }
    
        public virtual DagıtımOlcu DagıtımOlcu { get; set; }
        public virtual Faaliyet Faaliyet { get; set; }
        public virtual UrunMaliyet UrunMaliyet1 { get; set; }
        public virtual UrunMaliyet UrunMaliyet2 { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
